# _expected_mf_name_template_str = "^${starts_with}[a-fA-F0-9]{32}${extension}$$"
# extension = ".content"
# starts_with = "world_sql_content_"
# mf_zip_structure = { expected_dir_count = 0, expected_file_count = 1 }
# mf_finder_url = "https://www.bungie.net/Platform/Destiny/Manifest"
# mf_loc_base_url = "https://www.bungie.net"
# mf_lang = "en"
# api_key = "d4705221d56b4040b8c5c6b4ebd58757"
# force_update = true
# mf_dir_path = "/Users/oranqe/d2_project/manifest"
# mf_bak_ext = ".bak"
