# _expected_mf_name_template_str = """
#     '^${starts_with}[a-fA-F0-9]${extension}$$
# """
# extension = ".content"
# starts_with = "world_sql_content_"
# mf_finder_url = "https://www.bungie.net/Platform/Destiny/Manifest"
# mf_loc_base_url = "https://www.bungie.net"
# mf_lang = "en"
# api_key = "d4705221d56b4040b8c5c6b4ebd58757"
# mf_dir_path = "/Users/oranqe/d2_project/manifest"
# zip_path = "/Users/oranqe/d2_project/manifest.zip"
# mf_bak_ext = ".bak"
